### ISSUE TITLE
ER: install Marinetti as part of Spectrum installation for A2SERVER

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2cloud#17]
Now that MacIP has been demonstrated to work via macipgw, it would make sense to install Marinetti along with Spectrum in A2SERVER.

Marinetti is shipped as a single-file installer, plus a separate update to its TCPIP component. We would have to decide if we provide the installer for the user to run, or attempt to replicate its function (by figuring out what it installs where, or by asking Andrew Roughan) so that it is preinstalled along with is update (which seems preferable).

(Whoops, meant to file this under A2SERVER.)

**Comment by knghtbrd** [comment]
I definitely want to see this done, but as its an enhancement to 
existing functionality, I'd like to hold off just a little.  Our 
scripts are fairly monolithic in A2SERVER, and A2CLOUD seems like the 
obelisk from 2001, and I'd like to do something about that before too 
long.

If that seems to be dragging too much though, we should just do it.

**Comment by knghtbrd** [comment]
A2SERVER issue, and since filing this Ivan rewrote the entire Spectrum installation script anyway.  Need to look to see if that's resolved, but it's not an A2CLOUD bug.
