### ISSUE TITLE
TTYtter is dead - consider oystter

### ISSUE THREAD

**Issue by knghtbrd** [RasppleII/a2cloud#23]
According to the TTYtter page at http://www.floodgap.com/software/ttytter/, TTYtter is now a dead project.  You can find [oystter/oystter](https://github.com/oysttyer/oysttyer) forked as a replacement which the author endorses insofar as he endorses anything at all for Twitter.

We should probably migrate to oystter in the future as a result.

**Comment by knghtbrd** [comment]
Note, development on oystter is happening fast and frantic right now as they're just getting off the ground.  It might actually be good if we don't get to closing this one _immediately_.

The other possibility is not a descendent of TTYtter, but it's apparently it has a number of fans.  So [Nic0/tyrs](https://github.com/Nic0/tyrs) may also be worth a closer look even if it hasn't had as much recent development.

**Comment by IvanExpert** [comment]
Indeed, and interesting

**Comment by knghtbrd** [comment]
Resolved in A2CLOUD 1.9.0.
