### ISSUE TITLE
A2Pi will not work with Raspberry Pi 3B

### ISSUE THREAD

**Issue by knghtbrd** [RasppleII/a2cloud#26]
There are a couple of problems using Apple II Pi with the Raspberry Pi model 3B.
1. raspberrypi/firmware#553 will require a firmware update.  The issue notes several workarounds, but which of these is correct and actually works for everyone I cannot say yet.
2. You can add an overlay to swap this back to normal, but for some headdeskingly-crazy move, ttyAMA0 is now the Bluetooth radio.  If you want the GPIO UART, that's ttyS0.
3. If you're using the GPIO serial instead of a USB serial dongle because A2Pi card, the Pi 2B requires your Apple feed it 2.5 _amps_ of current.  Yes, really.

I think A2Pi is important for Raspple II and it needs to work well.  The use of the A2Pi card is perhaps less critical at this stage because you can't get them presently and they work just fine with the boards that were on sale at the time you could.  But I think we should get @dschmenk involved with the discussion of what maybe we can do about it.  :)

**Comment by knghtbrd** [comment]
I don't have an update on the baudrate bug and an effective workaround for it, but the way to detect a Pi 3's serial port is shown in raspi-config around line 740:

``` bash
      if [ -e /proc/device-tree/aliases/serial0 ]; then
        sed -i /boot/cmdline.txt -e "s/root=/console=serial0,115200 root=/"
      else
        sed -i /boot/cmdline.txt -e "s/root=/console=ttyAMA0,115200 root=/"
      fi
```

I'm still waiting for my replacement pi3, so I don't know if /dev/serial0 exists on that machine.  I know /dev/ttyS0 does.  Still, this is the officially supported way to detect whether or not the GPIO serial port is ttyAMA0 or not on the Pi.  I think I can deal with that.

As long as we're prepared to handle either one being in cmdline.txt, we'll be okay for the time being.  But we'll want to have support for assigning the Pi's GPIO serial for A2Pi when we do that.

**Comment by knghtbrd** [comment]
Additional information about the problem and potential solutions is here:

http://raspberrypi.stackexchange.com/questions/45570/how-do-i-make-serial-work-on-the-raspberry-pi3

Choices seem to be:
1. Use the reduced-capability UART for A2Pi
2. Disable bluetooth on the Pi 3
3. Reduce bluetooth's capabilities using the mini-UART

Maybe David has some thoughts?

Tagging @RasppleII/apple-ii-pi

**Comment by dschmenk** [comment]
I would suggest that the Pi3 only be supported with an external USB->serial port dongle on the Pi3 and a SSC on the Apple II. This is a fully compatible setup. Two reasons this makes sense: The GPIO UART on the Pi3 obviously has some issues. They might be worked out with additional system settings, but the other issue involves power draw from the A2Pi card. The Pi3 far exceeds what should be plugged into an Apple II slot. The Pi2 is probably on the edge, but I haven’t had any issues with my bench machine.

**Comment by knghtbrd** [comment]
What disabling Bluetooth on the Pi 3 does is let you use the full-function UART for the GPIO serial port.  I'd agree though that the Pi 3 with A2Pi Card is really reaching the point of diminishing returns.

We removed A2Pi from A2CLOUD for the jessie release for several reasons:
1. At least parts of the setup we had for it weren't jessie-compatible
2. Our setup was hard-wired to use GPIO serial, which didn't work on the Pi 3 at the time.
3. We did not want to delay a release for jessie to solve these problems.
4. A2Pi deserves to be its own top-tier project parallel to A2CLOUD, not shoehorned in to part of it.

This will create some conflict between your A2Pi repository and A2CLOUD because we're going to be installing our GSport (which I was working on this morning actually), but I'm actually thinking the emulators should also be spun out into a top tier project at some point because they just don't seem to belong as part of A2CLOUD either.  That's going to have to wait because pace is slow enough as it is.

I do intend to properly package it--we have a reprepro archive on blocksfree that I just need to automate an incoming directory for.  I plan to work with your package scripts as a base for that.  I should remember to ask though, did you have any patches to the SF codebase we should try and preserve?  We'll be applying one to rename config.txt to something more useful, but otherwise I don't have any plans to patch the existing GSport beyond what's needed to compile it.

The sort of stuff I'd want to do I believe Dagen's already working on anyway.

**Comment by knghtbrd** [comment]
@dschmenk resolved any issues with a2pi on newer boards ages ago, and we no longer install it as part of a2cloud.  I think it's safe to suggest this issue is effectively resolved.  I wouldn't mind giving folks access to the a2pi stuff on Raspple II systems in the future but as part of a2cloud it was always feeping creaturism.  It isn't a little component in a2cloud, it's a first class project of its own.
